
services:
  # --- Service Base de Données ---
  btl-db:
    image: postgres:15-alpine
    container_name: btl-db
    environment:
      # Lit les variables standard de l'image Postgres depuis .env
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      # Port Hôte (unique) -> Port Conteneur (fixe)
      - "${DB_PORT}:5432"
    networks:
      - btl-network
    volumes:
      - btl-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-btl_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # --- Service Backend (Django/FastAPI) ---
  btl-backend:
    build:
      context: .
      dockerfile: Dockerfile
    # On donne un nom d'image local pour que Docker puisse la réutiliser
    image: btl-app-base:latest
    container_name: btl-backend
    env_file: .env
    environment:
      - POSTGRES_HOST=btl-db
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      btl-db:
        condition: service_healthy
    networks:
      - btl-network
    volumes:
      - .:/app
      - btl-media-data:/app/media
      - btl-static-data:/app/staticfiles
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/btl/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  #Interface de gestion de PGadmin
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - btl-network
    depends_on:
      btl-db:
        condition: service_healthy
    restart: unless-stopped

  # --- CELERY WORKER ---
  btl-worker:
    # Au lieu de recompiler (build: .), on lui dit d'utiliser DIRECTEMENT l'image du backend !
    image: btl-app-base:latest
    container_name: btl-worker
    env_file: .env
    environment:
      - POSTGRES_HOST=btl-db
    command: >
      sh -c "celery -A config worker --loglevel=info"
    networks:
      - btl-network
    volumes:
      - .:/app
    depends_on:
      btl-backend:
        condition: service_started
      btl-db:
        condition: service_healthy
    restart: unless-stopped
# --- Réseau Interne---
networks:
  btl-network:
    driver: bridge

# --- Volumes Persistants ---
volumes:
  btl-postgres-data:
    name: btl-postgres-data
  btl-media-data:
    name: btl-media-data
  btl-static-data:
    name: btl-static-data

