services:
  # --- Service Base de Données ---
  btl-db:
    image: postgres:15-alpine
    container_name: btl-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - btl-network
    volumes:
      - btl-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # --- Service Redis (Le Broker pour Celery) ---
  btl-redis:
    image: redis:7-alpine
    container_name: btl-redis
    ports:
      - "6379:6379"
    networks:
      - btl-network
    restart: unless-stopped

  # --- Service Backend (Django) ---
  btl-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: btl-app-base:latest
    container_name: btl-backend
    env_file: .env
    environment:
      - POSTGRES_HOST=btl-db
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    depends_on:
      btl-db:
        condition: service_healthy
      btl-redis:                        # ✅ CORRECTION 1
        condition: service_started
    networks:
      - btl-network
    volumes:
      - btl-media-data:/app/media       # ✅ CORRECTION 2
      - btl-static-data:/app/static     # ✅ CORRECTION 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/api/btl/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # --- Interface de gestion PGadmin ---
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PG_ADMIN_PORT}:80"
    networks:
      - btl-network
    depends_on:
      btl-db:
        condition: service_healthy
    restart: unless-stopped

  # --- Service Celery Worker ---# --- Service Celery Worker ---
  btl-celery:
    image: btl-app-base:latest
    container_name: btl-celery
    # ─── AJOUT DE CETTE LIGNE POUR OUTREPASSER LE SCRIPT D'ENTRYPOINT DE MIGRATION ───
    entrypoint: [] 
    command: celery -A config worker --loglevel=info
    env_file: .env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      btl-db:
        condition: service_healthy
      btl-redis:
        condition: service_started
      # ─── AJOUTER LA DEPENDANCE SUR LE BACKEND POUR QU'IL ATTENDE LA FIN DES MIGRATIONS ───
      btl-backend:
        condition: service_healthy
    networks:
      - btl-network
# --- Réseau Interne ---
networks:
  btl-network:
    driver: bridge

# --- Volumes Persistants ---
volumes:
  btl-postgres-data:
    name: btl-postgres-data
  btl-media-data:
    name: btl-media-data
  btl-static-data:
    name: btl-static-data