# Generated by Django 6.0.5 on 2026-06-28 08:32

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("btl", "0045_gainpromotion_vente_achat_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampagneService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("nom", models.CharField(max_length=255)),
                (
                    "type_campagne_service",
                    models.CharField(
                        choices=[("SONDAGE", "Sondage / vérification de souscription")],
                        default="SONDAGE",
                        help_text="Détermine le formulaire et le modèle d'activité terrain utilisés.",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "campagne_produit_liee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pour une opération croisée produits + services chez la même entreprise.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campagnes_services_liees",
                        to="btl.campagne",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campagnes_services",
                        to="btl.entreprise",
                    ),
                ),
                (
                    "hotesses",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "Hotesse"},
                        related_name="campagnes_services_assignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True, related_name="campagnes_services", to="btl.site"
                    ),
                ),
                (
                    "superviseurs",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "Superviseur"},
                        related_name="campagnes_services_supervisees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalCampagneService",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("nom", models.CharField(max_length=255)),
                (
                    "type_campagne_service",
                    models.CharField(
                        choices=[("SONDAGE", "Sondage / vérification de souscription")],
                        default="SONDAGE",
                        help_text="Détermine le formulaire et le modèle d'activité terrain utilisés.",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campagne_produit_liee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Pour une opération croisée produits + services chez la même entreprise.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="btl.campagne",
                    ),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="btl.entreprise",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical campagne service",
                "verbose_name_plural": "historical campagne services",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalObjectifCampagneService",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Sondages réalisés, Souscriptions…",
                        max_length=150,
                    ),
                ),
                ("valeur_cible", models.PositiveIntegerField()),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campagne_service",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="services.campagneservice",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Objectif par site si renseigné, sinon objectif global de la campagne.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="btl.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical objectif campagne service",
                "verbose_name_plural": "historical objectif campagne services",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRecompenseService",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Forfait 5Go, Crédit communication 2000F",
                        max_length=255,
                    ),
                ),
                ("quantite_totale", models.PositiveIntegerField(default=0)),
                ("quantite_distribuee", models.PositiveIntegerField(default=0)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campagne_service",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="services.campagneservice",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical recompense service",
                "verbose_name_plural": "historical recompense services",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalService",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campagne_service",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="services.campagneservice",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical service",
                "verbose_name_plural": "historical services",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ObjectifCampagneService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Sondages réalisés, Souscriptions…",
                        max_length=150,
                    ),
                ),
                ("valeur_cible", models.PositiveIntegerField()),
                (
                    "campagne_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectifs",
                        to="services.campagneservice",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Objectif par site si renseigné, sinon objectif global de la campagne.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objectifs_services",
                        to="btl.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="RecompenseService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex: Forfait 5Go, Crédit communication 2000F",
                        max_length=255,
                    ),
                ),
                ("quantite_totale", models.PositiveIntegerField(default=0)),
                ("quantite_distribuee", models.PositiveIntegerField(default=0)),
                (
                    "campagne_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recompenses",
                        to="services.campagneservice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("nom", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "campagne_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="services.campagneservice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalSondage",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("nom_client", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "tranche_age",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MOINS_18", "-18 ans"),
                            ("18_25", "18-25 ans"),
                            ("26_35", "26-35 ans"),
                            ("36_50", "36-50 ans"),
                            ("PLUS_50", "+50 ans"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[("HOMME", "Homme"), ("FEMME", "Femme")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "possede_deja",
                    models.BooleanField(
                        default=False,
                        help_text="Le client avait-il déjà le service avant l'échange ?",
                    ),
                ),
                (
                    "a_souscrit",
                    models.BooleanField(
                        default=False,
                        help_text="A-t-il souscrit / installé le service suite à l'échange (si possede_deja=False) ?",
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campagne_service",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="services.campagneservice",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotesse",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"role": "Hotesse"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="btl.site",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sondage",
                "verbose_name_plural": "historical sondages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Sondage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("nom_client", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "tranche_age",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MOINS_18", "-18 ans"),
                            ("18_25", "18-25 ans"),
                            ("26_35", "26-35 ans"),
                            ("36_50", "36-50 ans"),
                            ("PLUS_50", "+50 ans"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        blank=True,
                        choices=[("HOMME", "Homme"), ("FEMME", "Femme")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "possede_deja",
                    models.BooleanField(
                        default=False,
                        help_text="Le client avait-il déjà le service avant l'échange ?",
                    ),
                ),
                (
                    "a_souscrit",
                    models.BooleanField(
                        default=False,
                        help_text="A-t-il souscrit / installé le service suite à l'échange (si possede_deja=False) ?",
                    ),
                ),
                (
                    "campagne_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sondages",
                        to="services.campagneservice",
                    ),
                ),
                (
                    "hotesse",
                    models.ForeignKey(
                        limit_choices_to={"role": "Hotesse"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sondages_effectues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sondages",
                        to="services.service",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sondages",
                        to="btl.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalGainRecompenseService",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("nom_client", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hotesse",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"role": "Hotesse"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="btl.site",
                    ),
                ),
                (
                    "recompense",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="services.recompenseservice",
                    ),
                ),
                (
                    "sondage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="services.sondage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical gain recompense service",
                "verbose_name_plural": "historical gain recompense services",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="GainRecompenseService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("nom_client", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "hotesse",
                    models.ForeignKey(
                        limit_choices_to={"role": "Hotesse"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gains_recompenses_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gains_recompenses_services",
                        to="btl.site",
                    ),
                ),
                (
                    "recompense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gains",
                        to="services.recompenseservice",
                    ),
                ),
                (
                    "sondage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gain",
                        to="services.sondage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
