# Generated by Django 6.0.5 on 2026-06-02 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degustation",
            name="note_gout",
            field=models.PositiveSmallIntegerField(
                help_text="Note entre 1 et 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaldegustation",
            name="note_gout",
            field=models.PositiveSmallIntegerField(
                help_text="Note entre 1 et 5",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
