# Generated by Django 6.0.5 on 2026-06-02 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0002_alter_degustation_note_gout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entreprise",
            name="couleur_primaire",
            field=models.CharField(
                default="#6366f1",
                help_text="Couleur principale (hex, ex: #6366f1)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="couleur_secondaire",
            field=models.CharField(
                default="#8b5cf6",
                help_text="Couleur secondaire (hex, ex: #8b5cf6)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="entreprise",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="URL du logo de l'entreprise", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalentreprise",
            name="couleur_primaire",
            field=models.CharField(
                default="#6366f1",
                help_text="Couleur principale (hex, ex: #6366f1)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="historicalentreprise",
            name="couleur_secondaire",
            field=models.CharField(
                default="#8b5cf6",
                help_text="Couleur secondaire (hex, ex: #8b5cf6)",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="historicalentreprise",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="URL du logo de l'entreprise", null=True
            ),
        ),
    ]
