# Generated by Django 5.2.6 on 2026-06-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0003_entreprise_couleur_primaire_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproduit",
            name="type_conditionnement",
            field=models.CharField(
                choices=[("UNITE", "À l'unité / Détail"), ("PACK", "En Pack")],
                default="UNITE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="type_conditionnement",
            field=models.CharField(
                choices=[("UNITE", "À l'unité / Détail"), ("PACK", "En Pack")],
                default="UNITE",
                max_length=10,
            ),
        ),
    ]
