# Generated by Django 5.2.6 on 2026-06-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0005_alter_entreprise_logo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalentreprise",
            name="logo_url",
            field=models.TextField(
                blank=True,
                help_text="Logo de l'entreprise (URL ou base64 data URI)",
                null=True,
            ),
        ),
    ]
