# Generated by Django 5.2.6 on 2026-06-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0006_alter_historicalentreprise_logo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="campagne",
            name="objectif_degustations",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campagne",
            name="objectif_ventes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcampagne",
            name="objectif_degustations",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcampagne",
            name="objectif_ventes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
