# Generated by Django 6.0.5 on 2026-06-10 09:31

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0010_alter_promotion_options_promotion_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodie',
            name='campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goodies', to='btl.campagne'),
        ),
        migrations.AddField(
            model_name='historicalgoodie',
            name='campagne',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.campagne'),
        ),
        migrations.CreateModel(
            name='GainPromotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantite_produits_concernes', models.PositiveIntegerField(default=1, help_text='Nombre de produits achetés pour déclencher ce gain (= quantite_requise de la règle)')),
                ('nom_client', models.CharField(blank=True, help_text='Prénom du client bénéficiaire (optionnel)', max_length=150, null=True)),
                ('tranche_age', models.CharField(blank=True, choices=[('MOINS_18', '-18 ans'), ('18_25', '18-25 ans'), ('26_35', '26-35 ans'), ('36_50', '36-50 ans'), ('PLUS_50', '+50 ans')], help_text="Tranche d'âge du client (optionnel)", max_length=20, null=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains_promotions', to='btl.campagne')),
                ('hotesse', models.ForeignKey(limit_choices_to={'role': 'Hotesse'}, on_delete=django.db.models.deletion.CASCADE, related_name='gains_promotions', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(help_text='La règle promotionnelle déclenchée', on_delete=django.db.models.deletion.CASCADE, related_name='gains', to='btl.promotion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains_promotions', to='btl.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalGainGoodie',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('degustation', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.degustation')),
                ('goodie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.goodie')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.promotion')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.site')),
            ],
            options={
                'verbose_name': 'historical gain goodie',
                'verbose_name_plural': 'historical gain goodies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalGainPromotion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantite_produits_concernes', models.PositiveIntegerField(default=1, help_text='Nombre de produits achetés pour déclencher ce gain (= quantite_requise de la règle)')),
                ('nom_client', models.CharField(blank=True, help_text='Prénom du client bénéficiaire (optionnel)', max_length=150, null=True)),
                ('tranche_age', models.CharField(blank=True, choices=[('MOINS_18', '-18 ans'), ('18_25', '18-25 ans'), ('26_35', '26-35 ans'), ('36_50', '36-50 ans'), ('PLUS_50', '+50 ans')], help_text="Tranche d'âge du client (optionnel)", max_length=20, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campagne', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.campagne')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hotesse', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'Hotesse'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(blank=True, db_constraint=False, help_text='La règle promotionnelle déclenchée', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.promotion')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.site')),
            ],
            options={
                'verbose_name': 'historical gain promotion',
                'verbose_name_plural': 'historical gain promotions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GainGoodie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('degustation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gain_goodie', to='btl.degustation')),
                ('goodie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains_sites', to='btl.goodie')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gains_goodies', to='btl.promotion')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gains_goodies', to='btl.site')),
            ],
            options={
                'unique_together': {('degustation', 'site', 'goodie')},
            },
        ),
    ]
