# Generated by Django 6.0.5 on 2026-06-11 10:16

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0013_vente_type_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalgaingoodie',
            name='nom_client',
            field=models.CharField(blank=True, help_text='Prénom du client bénéficiaire (optionnel)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalgaingoodie',
            name='produit_associe',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Produit associé offert avec ce goodie', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.produit'),
        ),
        migrations.AddField(
            model_name='historicalgaingoodie',
            name='quantite_produit',
            field=models.PositiveIntegerField(default=1, help_text='Quantité du produit associé remportée avec ce goodie'),
        ),
        migrations.AddField(
            model_name='historicalgoodie',
            name='produit_associe',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Produit offert avec ce goodie (ex: boisson)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.produit'),
        ),
        migrations.AddField(
            model_name='historicalgoodie',
            name='quantite_produit_associe',
            field=models.PositiveIntegerField(default=1, help_text='Quantité du produit associé à offrir avec ce goodie'),
        ),
        migrations.AddField(
            model_name='historicalvente',
            name='nom_client',
            field=models.CharField(blank=True, help_text='Optionnel ou Prénom', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicalvente',
            name='type_vente',
            field=models.CharField(choices=[('NORMAL', 'Vente normale'), ('GRATUIT', 'Offert avec goodie'), ('PROMOTION', 'Offert via promotion')], default='NORMAL', max_length=10),
        ),
        migrations.AddField(
            model_name='vente',
            name='nom_client',
            field=models.CharField(blank=True, help_text='Optionnel ou Prénom', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='degustation',
            name='note_gout',
            field=models.PositiveSmallIntegerField(help_text='Note entre 0 et 5 (0 = non évalué)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='historicaldegustation',
            name='note_gout',
            field=models.PositiveSmallIntegerField(help_text='Note entre 0 et 5 (0 = non évalué)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='vente',
            name='type_vente',
            field=models.CharField(choices=[('NORMAL', 'Vente normale'), ('GRATUIT', 'Offert avec goodie'), ('PROMOTION', 'Offert via promotion')], default='NORMAL', max_length=10),
        ),
        migrations.CreateModel(
            name='HistoricalObjectifSite',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(help_text="Date à laquelle l'objectif s'applique (ou date de début de période)")),
                ('objectif_degustations', models.PositiveIntegerField(default=0)),
                ('objectif_ventes', models.PositiveIntegerField(default=0)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hotesse', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'Hotesse'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.site')),
            ],
            options={
                'verbose_name': 'historical objectif site',
                'verbose_name_plural': 'historical objectif sites',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRapportJournalier',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('nb_degustations', models.PositiveIntegerField(default=0)),
                ('nb_ventes', models.PositiveIntegerField(default=0)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('email_envoye', models.BooleanField(default=False, help_text="True une fois l'email superviseur envoyé")),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hotesse', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'Hotesse'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.site')),
            ],
            options={
                'verbose_name': 'historical rapport journalier',
                'verbose_name_plural': 'historical rapport journaliers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSiteProduitPrix',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.produit')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.site')),
            ],
            options={
                'verbose_name': 'historical site produit prix',
                'verbose_name_plural': 'historical site produit prixs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ObjectifSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(help_text="Date à laquelle l'objectif s'applique (ou date de début de période)")),
                ('objectif_degustations', models.PositiveIntegerField(default=0)),
                ('objectif_ventes', models.PositiveIntegerField(default=0)),
                ('hotesse', models.ForeignKey(limit_choices_to={'role': 'Hotesse'}, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_sites', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='btl.site')),
            ],
            options={
                'unique_together': {('site', 'hotesse', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RapportJournalier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('nb_degustations', models.PositiveIntegerField(default=0)),
                ('nb_ventes', models.PositiveIntegerField(default=0)),
                ('chiffre_affaires', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('email_envoye', models.BooleanField(default=False, help_text="True une fois l'email superviseur envoyé")),
                ('hotesse', models.ForeignKey(limit_choices_to={'role': 'Hotesse'}, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_journaliers', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_journaliers', to='btl.site')),
            ],
            options={
                'unique_together': {('site', 'hotesse', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SiteProduitPrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_sites', to='btl.produit')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_produits', to='btl.site')),
            ],
            options={
                'unique_together': {('site', 'produit')},
            },
        ),
    ]
