# Generated by Django 6.0.5 on 2026-06-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0017_promotion_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrapportjournalier',
            name='nb_goodies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
