# Generated by Django 6.0.5 on 2026-06-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0018_alter_historicalrapportjournalier_nb_goodies'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE btl_historicalpromotion
                ADD COLUMN IF NOT EXISTS quantite_offerte integer NOT NULL DEFAULT 1;

                ALTER TABLE btl_promotion
                ADD COLUMN IF NOT EXISTS quantite_offerte integer NOT NULL DEFAULT 1;
            """,
            reverse_sql="""
                ALTER TABLE btl_historicalpromotion DROP COLUMN IF EXISTS quantite_offerte;
                ALTER TABLE btl_promotion DROP COLUMN IF EXISTS quantite_offerte;
            """,
            state_operations=[
                migrations.AddField(
                    model_name='historicalpromotion',
                    name='quantite_offerte',
                    field=models.PositiveIntegerField(default=1, help_text='Quantité de produits offerts / lots remis lors du déclenchement'),
                ),
                migrations.AddField(
                    model_name='promotion',
                    name='quantite_offerte',
                    field=models.PositiveIntegerField(default=1, help_text='Quantité de produits offerts / lots remis lors du déclenchement'),
                ),
            ],
        ),
    ]
