# Generated by Django 6.0.5 on 2026-06-18 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0018_alter_historicalrapportjournalier_nb_goodies'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaingoodie',
            name='hotesse',
            field=models.ForeignKey(blank=True, help_text='Utilisateur connecté ayant enregistré le gain', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gains_goodies_commandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalgaingoodie',
            name='hotesse',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur connecté ayant enregistré le gain', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
