# Generated by Django 6.0.5 on 2026-06-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0020_gaingoodie_hotesse_historicalgaingoodie_hotesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpromotion',
            name='quantite_offerte',
            field=models.PositiveIntegerField(default=1, help_text='Quantité de produits offerts / lots remis lors du déclenchement'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='quantite_offerte',
            field=models.PositiveIntegerField(default=1, help_text='Quantité de produits offerts / lots remis lors du déclenchement'),
        ),
    ]
