# Generated by Django 6.0.5 on 2026-06-21 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0021_set_base_manager_all_objects'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='note_gout_active',
            field=models.BooleanField(default=False, help_text='Active la saisie de la note du goût dans le formulaire de dégustation'),
        ),
        migrations.AddField(
            model_name='campagne',
            name='note_gout_max',
            field=models.PositiveSmallIntegerField(choices=[(5, '1 à 5'), (10, '1 à 10')], default=5, help_text='Échelle de notation du goût'),
        ),
        migrations.AddField(
            model_name='historicalcampagne',
            name='note_gout_active',
            field=models.BooleanField(default=False, help_text='Active la saisie de la note du goût dans le formulaire de dégustation'),
        ),
        migrations.AddField(
            model_name='historicalcampagne',
            name='note_gout_max',
            field=models.PositiveSmallIntegerField(choices=[(5, '1 à 5'), (10, '1 à 10')], default=5, help_text='Échelle de notation du goût'),
        ),
        migrations.AlterField(
            model_name='degustation',
            name='note_gout',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note du goût (configurable par campagne, null si non activé)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='historicaldegustation',
            name='note_gout',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Note du goût (configurable par campagne, null si non activé)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
