# Generated by Django 6.0.5 on 2026-06-17 15:34

from django.db import migrations, models


def add_historical_quantite_offerte_if_missing(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT column_name FROM information_schema.columns
                WHERE table_name = 'btl_historicalpromotion'
                  AND column_name = 'quantite_offerte'
            """)
            if cursor.fetchone():
                return
        schema_editor.execute(
            "ALTER TABLE btl_historicalpromotion ADD COLUMN quantite_offerte integer NOT NULL DEFAULT 1"
        )
    elif connection.vendor == 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute("PRAGMA table_info(btl_historicalpromotion)")
            rows = cursor.fetchall()
            if any(row[1] == 'quantite_offerte' for row in rows):
                return
        schema_editor.execute(
            "ALTER TABLE btl_historicalpromotion ADD COLUMN quantite_offerte integer NOT NULL DEFAULT 1"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0021_promotion_quantite_offerte'),
    ]

    operations = [
        migrations.RunPython(
            add_historical_quantite_offerte_if_missing,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='historicalpromotion',
                    name='quantite_offerte',
                    field=models.PositiveIntegerField(
                        default=1,
                        help_text="Nombre de produits offerts au client lors du déclenchement de l'offre",
                    ),
                ),
            ],
        ),
    ]
