# Generated by Django 6.0.5 on 2026-06-17 15:41

from django.db import migrations, models


def drop_gaingoodie_unique_together_if_exists(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != 'postgresql':
        return
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT constraint_name
            FROM information_schema.table_constraints
            WHERE table_name = 'btl_gaingoodie'
              AND constraint_type = 'UNIQUE'
              AND constraint_name LIKE '%degustation%'
        """)
        for (name,) in cursor.fetchall():
            cursor.execute(f'ALTER TABLE btl_gaingoodie DROP CONSTRAINT IF EXISTS "{name}"')


def add_promotion_quantite_offerte_if_missing(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == 'postgresql':
        with connection.cursor() as cursor:
            cursor.execute("""
                SELECT column_name FROM information_schema.columns
                WHERE table_name = 'btl_promotion'
                  AND column_name = 'quantite_offerte'
            """)
            if cursor.fetchone():
                return
        schema_editor.execute(
            "ALTER TABLE btl_promotion ADD COLUMN quantite_offerte integer NOT NULL DEFAULT 1"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0022_historicalpromotion_quantite_offerte'),
    ]

    operations = [
        migrations.RunPython(
            drop_gaingoodie_unique_together_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            add_promotion_quantite_offerte_if_missing,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='gaingoodie',
                    unique_together=set(),
                ),
                migrations.AddField(
                    model_name='promotion',
                    name='quantite_offerte',
                    field=models.PositiveIntegerField(
                        default=1,
                        help_text="Nombre de produits offerts au client lors du déclenchement de l'offre",
                    ),
                ),
                migrations.AddField(
                    model_name='historicalpromotion',
                    name='quantite_offerte',
                    field=models.PositiveIntegerField(
                        default=1,
                        help_text="Nombre de produits offerts au client lors du déclenchement de l'offre",
                    ),
                ),
            ],
        ),
    ]
