# Generated by Django 6.0.5 on 2026-06-21 21:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0022_add_note_gout_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='note_ambiance_active',
            field=models.BooleanField(default=False, help_text="Active la saisie de la note d'ambiance dans le formulaire de dégustation"),
        ),
        migrations.AddField(
            model_name='campagne',
            name='note_ambiance_max',
            field=models.PositiveSmallIntegerField(choices=[(5, '1 à 5'), (10, '1 à 10')], default=5, help_text="Échelle de notation de l'ambiance"),
        ),
        migrations.AddField(
            model_name='degustation',
            name='note_ambiance',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Note d'ambiance (configurable par campagne, null si non activé)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='historicalcampagne',
            name='note_ambiance_active',
            field=models.BooleanField(default=False, help_text="Active la saisie de la note d'ambiance dans le formulaire de dégustation"),
        ),
        migrations.AddField(
            model_name='historicalcampagne',
            name='note_ambiance_max',
            field=models.PositiveSmallIntegerField(choices=[(5, '1 à 5'), (10, '1 à 10')], default=5, help_text="Échelle de notation de l'ambiance"),
        ),
        migrations.AddField(
            model_name='historicaldegustation',
            name='note_ambiance',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Note d'ambiance (configurable par campagne, null si non activé)", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
