# Generated by Django 6.0.5 on 2026-06-22 05:05

from django.db import migrations
from datetime import datetime

def inject_historical_goodies(apps, schema_editor):
    GainGoodie = apps.get_model('btl', 'GainGoodie')
    Goodie = apps.get_model('btl', 'Goodie')
    Site = apps.get_model('btl', 'Site')
    RemoteUser = apps.get_model('btl', 'RemoteUser')
    StockGoodieSite = apps.get_model('btl', 'StockGoodieSite')
    RapportJournalier = apps.get_model('btl', 'RapportJournalier')

    DATA_TO_INJECT = [
        # --- RAPPORT DU 11 JUIN 2026 ---
        {"date": "2026-06-11", "hotesse_nom": "Sarah", "site": "LMB", "client": "Junior", "goodie": "Clé USB"},
        {"date": "2026-06-11", "hotesse_nom": "Frida La paix", "site": "Radisson", "client": "Dg", "goodie": "CAWET"},

        # --- RAPPORT DU MARDI 16 JUIN 2026 ---
        {"date": "2026-06-16", "hotesse_nom": "Sarah", "site": "LMB", "client": "Junior", "goodie": "Casquette"},
        {"date": "2026-06-16", "hotesse_nom": "Sarah", "site": "LMB", "client": "Smaelle", "goodie": "Décapsuleur"},
        {"date": "2026-06-16", "hotesse_nom": "Sarah", "site": "LMB", "client": "Christ", "goodie": "Décapsuleur"},
        {"date": "2026-06-16", "hotesse_nom": "Sarah", "site": "LMB", "client": "Christ", "goodie": "Clé USB"},
        {"date": "2026-06-16", "hotesse_nom": "Vénusia", "site": "LMB", "client": "Bienvenue", "goodie": "CAWET"},
        {"date": "2026-06-16", "hotesse_nom": "Vénusia", "site": "LMB", "client": "Océane", "goodie": "Clé USB"},
        {"date": "2026-06-16", "hotesse_nom": "Frida La paix", "site": "Radisson", "client": "Luc", "goodie": "Casquette"},
        {"date": "2026-06-16", "hotesse_nom": "Frida La paix", "site": "Radisson", "client": "Maria", "goodie": "CAWET"},
        {"date": "2026-06-16", "hotesse_nom": "Anne Tiphanie", "site": "Radisson", "client": "Alexandre", "goodie": "Casquette"},

        # --- RAPPORT DU MERCREDI 17 JUIN 2026 ---
        {"date": "2026-06-17", "hotesse_nom": "Sarah", "site": "LMB", "client": "Melvy'ne", "goodie": "Casquette"},
        {"date": "2026-06-17", "hotesse_nom": "Sarah", "site": "LMB", "client": "EKOMI EKOMI", "goodie": "Carnet"},
        {"date": "2026-06-17", "hotesse_nom": "Sarah", "site": "LMB", "client": "EKOMI EKOMI", "goodie": "CAWET"},
        {"date": "2026-06-17", "hotesse_nom": "Sarah", "site": "LMB", "client": "EKOMI EKOMI", "goodie": "Décapsuleur"},
        {"date": "2026-06-17", "hotesse_nom": "Vénusia", "site": "LMB", "client": "Osee", "goodie": "Ballon"},
        {"date": "2026-06-17", "hotesse_nom": "Vénusia", "site": "LMB", "client": "Owee", "goodie": "Clé USB"},
        {"date": "2026-06-17", "hotesse_nom": "Vénusia", "site": "LMB", "client": "Smaelle", "goodie": "Clé USB"},
        {"date": "2026-06-17", "hotesse_nom": "Vénusia", "site": "LMB", "client": "Elysee", "goodie": "Sac de sport"},
        {"date": "2026-06-17", "hotesse_nom": "Vénusia", "site": "LMB", "client": "Tresor", "goodie": "CAWET"},
        {"date": "2026-06-17", "hotesse_nom": "Vénusia", "site": "LMB", "client": "Smaeelle", "goodie": "Décapsuleur"},
    ]

    HOTESSE_EMAILS = {
        "Sarah": "sarahiboundou@gmail.com",       # REMPLACEZ PAR LES VRAIS EMAILS DE PRODUCTION
        "Vénusia": "mekinavenusia36@gmail.com",
        "Frida La paix": "kibissof@gmail.com",
        "Anne Tiphanie": "annemedzomobame@gmail.com",
        "Jennifer": "akengjennifer@gmail.com",
        "Bélinda": "belindantsele13@gmail.com",
    }

    for item in DATA_TO_INJECT:
        date_obj = datetime.strptime(item["date"], "%Y-%m-%d").date()
        email = HOTESSE_EMAILS.get(item["hotesse_nom"])
        
        if not email:
            continue

        try:
            hotesse_user = RemoteUser.objects.get(email=email)
            site_obj = Site.objects.filter(nom__icontains=item["site"]).first()
            goodie_obj = Goodie.objects.filter(nom__icontains=item["goodie"]).first()

            if not site_obj or not goodie_obj:
                continue

            _, created = GainGoodie.objects.get_or_create(
                created_at=date_obj,
                hotesse=hotesse_user,
                site=site_obj,
                goodie=goodie_obj,
                nom_client=item["client"],
                defaults={
                    "quantite_produit": 1,
                    "produit_associe": goodie_obj.produit_associe
                }
            )

            if created:
                stock = StockGoodieSite.objects.filter(site=site_obj, goodie=goodie_obj).first()
                if stock and stock.quantite_restante > 0:
                    stock.quantite_restante -= 1
                    stock.save()

                rapport, r_created = RapportJournalier.objects.get_or_create(
                    site=site_obj,
                    hotesse=hotesse_user,
                    date=date_obj
                )
                rapport.nb_goodies += 1
                rapport.save()

        except Exception:
            continue

def reverse_historical_goodies(apps, schema_editor):
    pass



class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0023_campagne_note_ambiance_active_and_more'),
    ]

    operations = [
        migrations.RunPython(inject_historical_goodies, reverse_historical_goodies),
    ]
