# Generated by Django 6.0.5 on 2026-06-17 17:16

from django.db import migrations


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0024_alter_gaingoodie_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(noop, reverse_code=migrations.RunPython.noop),
    ]
