# Generated by Django 6.0.5 on 2026-06-17 20:20

from django.db import migrations


def noop(apps, schema_editor):
    """No-op function for merge migration."""
    pass


class Migration(migrations.Migration):
    """
    Migration de fusion pour résoudre le conflit entre:
    - 0019_fix_gaingoodie_unique_constraint
    - 0025_historicalpromotion_quantite_offerte_and_more
    """

    dependencies = [
        ('btl', '0019_fix_gaingoodie_unique_constraint'),
        ('btl', '0025_historicalpromotion_quantite_offerte_and_more'),
    ]

    operations = [
        migrations.RunPython(noop, reverse_code=migrations.RunPython.noop),
    ]
