# Generated by Django 6.0.5

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0019_historicalpromotion_quantite_offerte_and_more'),
        ('btl', '0025_historicalpromotion_quantite_offerte_and_more'),
    ]

    operations = [
    ]
