# Generated by Django 6.0.5 on 2026-06-22 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0024_auto_20260622_0605'),
        ('btl', '0027_promotion_conditionnement'),
    ]

    operations = [
    ]
