# Generated by Django 6.0.5 on 2026-06-22 16:23

import datetime
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0029_add_jour_animation'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jouranimation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='historicalpromotion',
            name='type_promotion',
            field=models.CharField(choices=[('OFFERT', 'Produit offert'), ('GAGNE', 'À gagner / Bon cadeau'), ('TIRAGE', 'Tirage à la roue')], default='OFFERT', max_length=10),
        ),
        migrations.AlterField(
            model_name='jouranimation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jouranimation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='type_promotion',
            field=models.CharField(choices=[('OFFERT', 'Produit offert'), ('GAGNE', 'À gagner / Bon cadeau'), ('TIRAGE', 'Tirage à la roue')], default='OFFERT', max_length=10),
        ),
        migrations.CreateModel(
            name='HistoricalJourAnimation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(help_text="Date de l'animation")),
                ('heure_ouverture', models.TimeField(default=datetime.time(8, 0))),
                ('heure_fermeture', models.TimeField(default=datetime.time(18, 0))),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campagne', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.campagne')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, help_text='Laisser vide pour appliquer à tous les sites de la campagne.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.site')),
            ],
            options={
                'verbose_name': 'historical jour animation',
                'verbose_name_plural': 'historical jour animations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
