# Generated by Django 6.0.5 on 2026-06-23 11:01

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0032_add_pointage_livraison_goodies_jour'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='livraisongoodiesjour',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pointage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='rapportconfig',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='livraisongoodiesjour',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pointage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='livraisongoodiesjour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='livraisongoodiesjour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='jour',
            field=models.ForeignKey(blank=True, help_text="Jour d'animation associé (optionnel, pour lier aux horaires prévus)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pointages', to='btl.jouranimation'),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalLivraisonGoodiesJour',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(help_text='Date de la livraison')),
                ('quantite_apportee', models.PositiveIntegerField(default=0, help_text='Nombre de goodies apportés sur le site ce jour')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('enregistre_par', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goodie', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.goodie')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.site')),
            ],
            options={
                'verbose_name': 'historical Livraison goodies (jour)',
                'verbose_name_plural': 'historical Livraisons goodies (jour)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPointage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField(help_text='Date du pointage')),
                ('heure_arrivee', models.TimeField(blank=True, help_text="Heure de pointage à l'arrivée", null=True)),
                ('heure_depart', models.TimeField(blank=True, help_text='Heure de pointage au départ', null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hotesse', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role': 'Hotesse'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('jour', models.ForeignKey(blank=True, db_constraint=False, help_text="Jour d'animation associé (optionnel, pour lier aux horaires prévus)", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.jouranimation')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.site')),
            ],
            options={
                'verbose_name': 'historical Pointage hôtesse',
                'verbose_name_plural': 'historical Pointages hôtesses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRapportConfig',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('titre_personnalise', models.CharField(blank=True, help_text='Titre personnalisé affiché sur la page de couverture (remplace le nom de la campagne)', max_length=255, null=True)),
                ('sous_titre_personnalise', models.CharField(blank=True, help_text="Sous-titre personnalisé (ex: 'Rapport Confidentiel')", max_length=255, null=True)),
                ('show_kpi_degustations', models.BooleanField(default=True, help_text='Afficher le KPI consommations')),
                ('show_kpi_ventes', models.BooleanField(default=True, help_text='Afficher le KPI distributions/ventes')),
                ('show_kpi_ca', models.BooleanField(default=True, help_text="Afficher le KPI chiffre d'affaires")),
                ('show_kpi_goodies', models.BooleanField(default=True, help_text='Afficher le KPI goodies distribués')),
                ('show_kpi_sites', models.BooleanField(default=True, help_text='Afficher le KPI nombre de sites actifs')),
                ('show_section_offres_promo', models.BooleanField(default=True, help_text='Section : Offres promotionnelles')),
                ('show_section_gains_goodies', models.BooleanField(default=True, help_text='Section : Gains de goodies par site')),
                ('show_section_perf_hotesses', models.BooleanField(default=True, help_text='Section : Performance des hôtesses (rapport interne)')),
                ('show_section_perf_sites', models.BooleanField(default=True, help_text='Section : Performances par site')),
                ('show_section_goodies_par_site', models.BooleanField(default=True, help_text='Section : Goodies distribués par site')),
                ('show_section_offres_par_hotesse', models.BooleanField(default=True, help_text='Section : Offres par hôtesse (rapport interne)')),
                ('show_col_ca', models.BooleanField(default=True, help_text="Colonne : Chiffre d'affaires dans les tableaux")),
                ('show_col_goodies', models.BooleanField(default=True, help_text='Colonne : Goodies dans les tableaux')),
                ('show_col_promo_details', models.BooleanField(default=True, help_text='Colonne : Détails promotionnels (offerts, tickets)')),
                ('show_col_performance', models.BooleanField(default=True, help_text='Colonne : Taux de performance dans les tableaux')),
                ('show_logo', models.BooleanField(default=True, help_text="Afficher le logo de l'entreprise")),
                ('show_equipe_hotesses', models.BooleanField(default=True, help_text='Inclure les données individuelles des hôtesses (rapport interne)')),
                ('inclure_notes_sensorielles', models.BooleanField(default=False, help_text='Inclure les statistiques sensorielles (note goût, ambiance)')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('campagne', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='btl.campagne')),
                ('configure_par', models.ForeignKey(blank=True, db_constraint=False, help_text='Superviseur ou admin ayant défini cette configuration', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Configuration rapport',
                'verbose_name_plural': 'historical Configurations rapports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
