# Generated by Django 6.0.5 on 2026-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0033_alter_livraisongoodiesjour_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="observations_manuelles",
            field=models.TextField(
                blank=True,
                help_text="Observations libres ajoutées manuellement par le superviseur, affichées dans le rapport",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_col_intention_achat",
            field=models.BooleanField(
                default=True, help_text="Colonne : Intention d'achat"
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_col_nom_client",
            field=models.BooleanField(
                default=True,
                help_text="Colonne : Nom du client dans le détail des dégustations",
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_col_tranche_age",
            field=models.BooleanField(
                default=True, help_text="Colonne : Tranche d'âge du client"
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_observations",
            field=models.BooleanField(
                default=True,
                help_text="Afficher la section Observations dans le rapport",
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_section_detail_degustations",
            field=models.BooleanField(
                default=False,
                help_text="Section : Détail des dégustations — reprend les données saisies par les hôtesses sur le terrain (rapport interne)",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="observations_manuelles",
            field=models.TextField(
                blank=True,
                help_text="Observations libres ajoutées manuellement par le superviseur, affichées dans le rapport",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_col_intention_achat",
            field=models.BooleanField(
                default=True, help_text="Colonne : Intention d'achat"
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_col_nom_client",
            field=models.BooleanField(
                default=True,
                help_text="Colonne : Nom du client dans le détail des dégustations",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_col_tranche_age",
            field=models.BooleanField(
                default=True, help_text="Colonne : Tranche d'âge du client"
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_observations",
            field=models.BooleanField(
                default=True,
                help_text="Afficher la section Observations dans le rapport",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_section_detail_degustations",
            field=models.BooleanField(
                default=False,
                help_text="Section : Détail des dégustations — reprend les données saisies par les hôtesses sur le terrain (rapport interne)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrapportconfig",
            name="inclure_notes_sensorielles",
            field=models.BooleanField(
                default=False,
                help_text="Inclure les notes de goût et d'ambiance dans le détail des dégustations",
            ),
        ),
        migrations.AlterField(
            model_name="rapportconfig",
            name="inclure_notes_sensorielles",
            field=models.BooleanField(
                default=False,
                help_text="Inclure les notes de goût et d'ambiance dans le détail des dégustations",
            ),
        ),
    ]
