# Generated by Django 6.0.5 on 2026-06-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0034_rapport_config_observations_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_section_horaires_sites",
            field=models.BooleanField(
                default=True,
                help_text="Section : Horaires d'ouverture des sites de la campagne",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_section_horaires_sites",
            field=models.BooleanField(
                default=True,
                help_text="Section : Horaires d'ouverture des sites de la campagne",
            ),
        ),
    ]
