# Generated by Django 6.0.5 on 2026-06-23 17:29

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0035_rapport_config_horaires_sites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrapportjournalier",
            name="email_envoye",
        ),
        migrations.RemoveField(
            model_name="rapportjournalier",
            name="email_envoye",
        ),
        migrations.AddField(
            model_name="historicalrapportjournalier",
            name="avis_consommateurs",
            field=models.TextField(
                blank=True,
                help_text="Avis qualitatif des consommateurs sur le produit (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalier",
            name="heure_arrivee",
            field=models.TimeField(
                blank=True,
                help_text="Reprise automatique du pointage d'arrivée",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalier",
            name="heure_depart",
            field=models.TimeField(
                blank=True,
                help_text="Reprise automatique du pointage de départ",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalier",
            name="nombre_personnes_touchees",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nombre total de personnes abordées/touchées dans la journée (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalier",
            name="observation_generale",
            field=models.TextField(
                blank=True,
                help_text="Observation générale de la journée (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalier",
            name="stock_initial_magasin",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Stock produit en magasin en début de journée (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalier",
            name="avis_consommateurs",
            field=models.TextField(
                blank=True,
                help_text="Avis qualitatif des consommateurs sur le produit (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalier",
            name="heure_arrivee",
            field=models.TimeField(
                blank=True,
                help_text="Reprise automatique du pointage d'arrivée",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalier",
            name="heure_depart",
            field=models.TimeField(
                blank=True,
                help_text="Reprise automatique du pointage de départ",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalier",
            name="nombre_personnes_touchees",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nombre total de personnes abordées/touchées dans la journée (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalier",
            name="observation_generale",
            field=models.TextField(
                blank=True,
                help_text="Observation générale de la journée (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalier",
            name="stock_initial_magasin",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Stock produit en magasin en début de journée (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalRapportJournalierConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "show_pointage",
                    models.BooleanField(
                        default=True, help_text="Section : Heures d'arrivée / départ"
                    ),
                ),
                (
                    "show_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Section : Stock magasin en début de journée",
                    ),
                ),
                (
                    "show_ventes_detail",
                    models.BooleanField(
                        default=True,
                        help_text="Section : Détail des ventes (promo / hors promo)",
                    ),
                ),
                (
                    "show_ugs_recus",
                    models.BooleanField(
                        default=True,
                        help_text="Section : UGs (goodies) reçus sur le site",
                    ),
                ),
                (
                    "show_ugs_distribues",
                    models.BooleanField(
                        default=True, help_text="Section : UGs (goodies) distribués"
                    ),
                ),
                (
                    "show_ugs_restants",
                    models.BooleanField(
                        default=True, help_text="Section : UGs (goodies) restants"
                    ),
                ),
                (
                    "show_degustation",
                    models.BooleanField(
                        default=True,
                        help_text="Section : Détail des dégustations du jour",
                    ),
                ),
                (
                    "show_personnes_touchees",
                    models.BooleanField(
                        default=True, help_text="Section : Nombre de personnes touchées"
                    ),
                ),
                (
                    "show_avis_consommateurs",
                    models.BooleanField(
                        default=True, help_text="Section : Avis des consommateurs"
                    ),
                ),
                (
                    "show_observation_generale",
                    models.BooleanField(
                        default=True, help_text="Section : Observation générale"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campagne",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="btl.campagne",
                    ),
                ),
                (
                    "configure_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Superviseur ou admin ayant défini cette configuration",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Configuration rapport journalier",
                "verbose_name_plural": "historical Configurations rapports journaliers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="RapportJournalierConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "show_pointage",
                    models.BooleanField(
                        default=True, help_text="Section : Heures d'arrivée / départ"
                    ),
                ),
                (
                    "show_stock",
                    models.BooleanField(
                        default=True,
                        help_text="Section : Stock magasin en début de journée",
                    ),
                ),
                (
                    "show_ventes_detail",
                    models.BooleanField(
                        default=True,
                        help_text="Section : Détail des ventes (promo / hors promo)",
                    ),
                ),
                (
                    "show_ugs_recus",
                    models.BooleanField(
                        default=True,
                        help_text="Section : UGs (goodies) reçus sur le site",
                    ),
                ),
                (
                    "show_ugs_distribues",
                    models.BooleanField(
                        default=True, help_text="Section : UGs (goodies) distribués"
                    ),
                ),
                (
                    "show_ugs_restants",
                    models.BooleanField(
                        default=True, help_text="Section : UGs (goodies) restants"
                    ),
                ),
                (
                    "show_degustation",
                    models.BooleanField(
                        default=True,
                        help_text="Section : Détail des dégustations du jour",
                    ),
                ),
                (
                    "show_personnes_touchees",
                    models.BooleanField(
                        default=True, help_text="Section : Nombre de personnes touchées"
                    ),
                ),
                (
                    "show_avis_consommateurs",
                    models.BooleanField(
                        default=True, help_text="Section : Avis des consommateurs"
                    ),
                ),
                (
                    "show_observation_generale",
                    models.BooleanField(
                        default=True, help_text="Section : Observation générale"
                    ),
                ),
                (
                    "campagne",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rapport_journalier_config",
                        to="btl.campagne",
                    ),
                ),
                (
                    "configure_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Superviseur ou admin ayant défini cette configuration",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configs_rapports_journaliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration rapport journalier",
                "verbose_name_plural": "Configurations rapports journaliers",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
