# Generated by Django 6.0.5 on 2026-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0036_rapport_journalier_enrichment"),
    ]

    operations = [
        migrations.AddField(
            model_name="degustation",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[("HOMME", "Homme"), ("FEMME", "Femme")],
                help_text="Genre du client (Homme/Femme) — nullable pour compatibilité avec les anciennes saisies",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaldegustation",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[("HOMME", "Homme"), ("FEMME", "Femme")],
                help_text="Genre du client (Homme/Femme) — nullable pour compatibilité avec les anciennes saisies",
                max_length=10,
                null=True,
            ),
        ),
    ]
