# Generated by Django 6.0.5 on 2026-06-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0037_degustation_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrapportjournalierconfig",
            name="show_genre",
            field=models.BooleanField(
                default=True,
                help_text="Section : Répartition par genre (Hommes/Femmes) des dégustations",
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalierconfig",
            name="show_genre",
            field=models.BooleanField(
                default=True,
                help_text="Section : Répartition par genre (Hommes/Femmes) des dégustations",
            ),
        ),
    ]
