# Generated by Django 6.0.5 on 2026-06-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0038_rapport_journalier_config_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_kpi_ventes_hors_promo",
            field=models.BooleanField(
                default=True, help_text="Afficher le KPI ventes hors promotion"
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalier",
            name="nombre_boissons_gratuites",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nombre de boissons offertes gratuitement sur le site (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalier",
            name="stock_boissons",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Stock de boissons disponible sur le site (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalierconfig",
            name="show_boissons_gratuites",
            field=models.BooleanField(
                default=True,
                help_text="Section : Nombre de boissons gratuites distribuées",
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalierconfig",
            name="show_stock_boissons",
            field=models.BooleanField(
                default=True, help_text="Section : Stock de boissons du site"
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_kpi_ventes_hors_promo",
            field=models.BooleanField(
                default=True, help_text="Afficher le KPI ventes hors promotion"
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalier",
            name="nombre_boissons_gratuites",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Nombre de boissons offertes gratuitement sur le site (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalier",
            name="stock_boissons",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Stock de boissons disponible sur le site (saisie manuelle)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalierconfig",
            name="show_boissons_gratuites",
            field=models.BooleanField(
                default=True,
                help_text="Section : Nombre de boissons gratuites distribuées",
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalierconfig",
            name="show_stock_boissons",
            field=models.BooleanField(
                default=True, help_text="Section : Stock de boissons du site"
            ),
        ),
        migrations.AlterField(
            model_name="historicalrapportconfig",
            name="show_kpi_degustations",
            field=models.BooleanField(default=True, help_text="Afficher le KPI ventes"),
        ),
        migrations.AlterField(
            model_name="historicalrapportconfig",
            name="show_kpi_ventes",
            field=models.BooleanField(
                default=True, help_text="Afficher le KPI produits offerts"
            ),
        ),
        migrations.AlterField(
            model_name="rapportconfig",
            name="show_kpi_degustations",
            field=models.BooleanField(default=True, help_text="Afficher le KPI ventes"),
        ),
        migrations.AlterField(
            model_name="rapportconfig",
            name="show_kpi_ventes",
            field=models.BooleanField(
                default=True, help_text="Afficher le KPI produits offerts"
            ),
        ),
    ]
