# Generated by Django 6.0.5 on 2026-06-24 01:49

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0039_historicalrapportconfig_show_kpi_ventes_hors_promo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrapportjournalier",
            name="nombre_boissons_gratuites",
        ),
        migrations.RemoveField(
            model_name="historicalrapportjournalier",
            name="stock_boissons",
        ),
        migrations.RemoveField(
            model_name="rapportjournalier",
            name="nombre_boissons_gratuites",
        ),
        migrations.RemoveField(
            model_name="rapportjournalier",
            name="stock_boissons",
        ),
        migrations.CreateModel(
            name="HistoricalDonneesSiteJour",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField(help_text="Date des données")),
                (
                    "stock_boissons",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Stock de boissons disponible sur le site (saisie manuelle)",
                        null=True,
                    ),
                ),
                (
                    "nombre_boissons_gratuites",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre de boissons offertes gratuitement sur le site (saisie manuelle)",
                        null=True,
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="btl.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Données site (jour)",
                "verbose_name_plural": "historical Données sites (jour)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DonneesSiteJour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField(help_text="Date des données")),
                (
                    "stock_boissons",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Stock de boissons disponible sur le site (saisie manuelle)",
                        null=True,
                    ),
                ),
                (
                    "nombre_boissons_gratuites",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Nombre de boissons offertes gratuitement sur le site (saisie manuelle)",
                        null=True,
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donnees_sites_jour_enregistrees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donnees_jour",
                        to="btl.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Données site (jour)",
                "verbose_name_plural": "Données sites (jour)",
                "ordering": ["-date"],
                "unique_together": {("site", "date")},
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
