# Generated by Django 6.0.5 on 2026-06-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "btl",
            "0040_remove_historicalrapportjournalier_nombre_boissons_gratuites_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="donneessitejour",
            name="conditionnement",
            field=models.CharField(
                choices=[("UNITE", "À l'unité / Détail"), ("PACK", "En Pack")],
                default="UNITE",
                help_text="Conditionnement du stock de boissons et des boissons gratuites (à l'unité ou en pack), selon la configuration des produits de l'entreprise",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicaldonneessitejour",
            name="conditionnement",
            field=models.CharField(
                choices=[("UNITE", "À l'unité / Détail"), ("PACK", "En Pack")],
                default="UNITE",
                help_text="Conditionnement du stock de boissons et des boissons gratuites (à l'unité ou en pack), selon la configuration des produits de l'entreprise",
                max_length=10,
            ),
        ),
    ]
