# Generated by Django 6.0.5 on 2026-06-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0021_alter_historicalpromotion_quantite_offerte_and_more'),
        ('btl', '0040_remove_historicalrapportjournalier_nombre_boissons_gratuites_and_more'),
    ]

    operations = [
    ]
