# Generated by Django 6.0.5 on 2026-06-24 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btl', '0041_donneessitejour_conditionnement_and_more'),
        ('btl', '0041_merge_20260624_0703'),
    ]

    operations = [
    ]
