# Generated by Django 6.0.5 on 2026-06-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0042_merge_20260624_0833"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_section_stock_boissons",
            field=models.BooleanField(
                default=True,
                help_text="Section : Stock de boissons & boissons gratuites par site",
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_section_ugs_livraisons",
            field=models.BooleanField(
                default=True,
                help_text="Section : UGs (goodies) reçus / distribués / restants par site",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_section_stock_boissons",
            field=models.BooleanField(
                default=True,
                help_text="Section : Stock de boissons & boissons gratuites par site",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_section_ugs_livraisons",
            field=models.BooleanField(
                default=True,
                help_text="Section : UGs (goodies) reçus / distribués / restants par site",
            ),
        ),
    ]
