# Generated by Django 6.0.5 on 2026-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0043_historicalrapportconfig_show_section_stock_boissons_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrapportjournalierconfig",
            name="show_notes_degustation",
            field=models.BooleanField(
                default=True,
                help_text="Section : Notes moyennes de goût et d'ambiance (si activées sur la campagne)",
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportjournalierconfig",
            name="show_tranche_age",
            field=models.BooleanField(
                default=True,
                help_text="Section : Répartition par tranche d'âge des dégustations",
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalierconfig",
            name="show_notes_degustation",
            field=models.BooleanField(
                default=True,
                help_text="Section : Notes moyennes de goût et d'ambiance (si activées sur la campagne)",
            ),
        ),
        migrations.AddField(
            model_name="rapportjournalierconfig",
            name="show_tranche_age",
            field=models.BooleanField(
                default=True,
                help_text="Section : Répartition par tranche d'âge des dégustations",
            ),
        ),
    ]
