# Generated by Django 6.0.5 on 2026-06-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "btl",
            "0044_historicalrapportjournalierconfig_show_notes_degustation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gainpromotion",
            name="vente_achat",
            field=models.OneToOneField(
                blank=True,
                help_text="Vente NORMAL correspondant à l'achat ayant déclenché ce gain",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gain_promotion",
                to="btl.vente",
            ),
        ),
        migrations.AddField(
            model_name="historicalgainpromotion",
            name="vente_achat",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Vente NORMAL correspondant à l'achat ayant déclenché ce gain",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="btl.vente",
            ),
        ),
    ]
