# Generated by Django 6.0.5 on 2026-06-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0045_gainpromotion_vente_achat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="campagne",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="btl.campagne",
            ),
        ),
    ]
