# Generated by Django 6.0.5 on 2026-07-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0049_historicallivraisongoodiesjour_est_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_section_graphiques",
            field=models.BooleanField(
                default=True,
                help_text="Section : Graphiques de comparaison par site (ventes, dégustations)",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_section_graphiques",
            field=models.BooleanField(
                default=True,
                help_text="Section : Graphiques de comparaison par site (ventes, dégustations)",
            ),
        ),
    ]
