# Generated by Django 6.0.5 on 2026-07-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0050_historicalrapportconfig_show_section_graphiques_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvente",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[("HOMME", "Homme"), ("FEMME", "Femme")],
                help_text="Genre du client (optionnel)",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalvente",
            name="tranche_age",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MOINS_18", "-18 ans"),
                    ("18_25", "18-25 ans"),
                    ("26_35", "26-35 ans"),
                    ("36_50", "36-50 ans"),
                    ("PLUS_50", "+50 ans"),
                ],
                help_text="Tranche d'âge du client (optionnel)",
                max_length=20,
                null=True,
            ),
        ),
    ]
