# Generated by Django 6.0.5 on 2026-07-08 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0051_historicalvente_genre_historicalvente_tranche_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvente",
            name="note_ambiance",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Note d'ambiance (configurable par campagne, null si non activé)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="historicalvente",
            name="note_gout",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Note du goût (configurable par campagne, null si non activé)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="note_ambiance",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Note d'ambiance (configurable par campagne, null si non activé)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="note_gout",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Note du goût (configurable par campagne, null si non activé)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
