# Generated by Django 6.0.5 on 2026-07-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0052_historicalvente_note_ambiance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donneessitejour",
            name="est_report_gratuites",
            field=models.BooleanField(
                default=False,
                help_text="Créé automatiquement par report du restant de boissons gratuites de la veille (tâche nocturne)",
            ),
        ),
        migrations.AddField(
            model_name="donneessitejour",
            name="quantite_gratuites_recue",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantité de boissons gratuites reçues/disponibles sur le site ce jour (saisie manuelle, ou reportée automatiquement du restant de la veille)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaldonneessitejour",
            name="est_report_gratuites",
            field=models.BooleanField(
                default=False,
                help_text="Créé automatiquement par report du restant de boissons gratuites de la veille (tâche nocturne)",
            ),
        ),
        migrations.AddField(
            model_name="historicaldonneessitejour",
            name="quantite_gratuites_recue",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Quantité de boissons gratuites reçues/disponibles sur le site ce jour (saisie manuelle, ou reportée automatiquement du restant de la veille)",
                null=True,
            ),
        ),
    ]
