# Generated by Django 6.0.5 on 2026-07-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0053_donneessitejour_est_report_gratuites_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_kpi_personnes_touchees",
            field=models.BooleanField(
                default=True,
                help_text="Afficher le KPI personnes touchées (clients ayant participé à la campagne)",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_kpi_personnes_touchees",
            field=models.BooleanField(
                default=True,
                help_text="Afficher le KPI personnes touchées (clients ayant participé à la campagne)",
            ),
        ),
    ]
