# Generated by Django 6.0.5 on 2026-07-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0055_donneessitejour_conditionnement_gratuites"),
    ]

    operations = [
        migrations.AddField(
            model_name="campagne",
            name="objectif_goodies",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Objectif de goodies gagnés par les clients sur toute la période de la campagne",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campagne",
            name="objectif_gratuites",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Objectif de boissons gratuites distribuées sur toute la période de la campagne",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcampagne",
            name="objectif_goodies",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Objectif de goodies gagnés par les clients sur toute la période de la campagne",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalcampagne",
            name="objectif_gratuites",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Objectif de boissons gratuites distribuées sur toute la période de la campagne",
                null=True,
            ),
        ),
    ]
