# Generated by Django 6.0.5 on 2026-07-13 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("btl", "0056_campagne_objectif_goodies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_section_boissons_total",
            field=models.BooleanField(
                default=True,
                help_text="Section : Total boissons reçues / offertes par site (en canettes, récapitulatif campagne)",
            ),
        ),
        migrations.AddField(
            model_name="historicalrapportconfig",
            name="show_section_goodies_detail",
            field=models.BooleanField(
                default=True,
                help_text="Section : Détail goodies par site et par nom (tableau Site / Goodie / Reçu / Gagné / Restant)",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_section_boissons_total",
            field=models.BooleanField(
                default=True,
                help_text="Section : Total boissons reçues / offertes par site (en canettes, récapitulatif campagne)",
            ),
        ),
        migrations.AddField(
            model_name="rapportconfig",
            name="show_section_goodies_detail",
            field=models.BooleanField(
                default=True,
                help_text="Section : Détail goodies par site et par nom (tableau Site / Goodie / Reçu / Gagné / Restant)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrapportconfig",
            name="show_section_goodies_par_site",
            field=models.BooleanField(
                default=True,
                help_text="Section : Goodies distribués par site (tableau de synthèse : goodies directs, offres promo, total avantages)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalrapportconfig",
            name="show_section_stock_boissons",
            field=models.BooleanField(
                default=True,
                help_text="Section : Stock de boissons & boissons gratuites par site (détail jour par jour)",
            ),
        ),
        migrations.AlterField(
            model_name="rapportconfig",
            name="show_section_goodies_par_site",
            field=models.BooleanField(
                default=True,
                help_text="Section : Goodies distribués par site (tableau de synthèse : goodies directs, offres promo, total avantages)",
            ),
        ),
        migrations.AlterField(
            model_name="rapportconfig",
            name="show_section_stock_boissons",
            field=models.BooleanField(
                default=True,
                help_text="Section : Stock de boissons & boissons gratuites par site (détail jour par jour)",
            ),
        ),
    ]
